add debugging
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>

diff --git a/.github/workflows/theia-zowe-explorer-ci.yml b/.github/workflows/theia-zowe-explorer-ci.yml
--- a/.github/workflows/theia-zowe-explorer-ci.yml
+++ b/.github/workflows/theia-zowe-explorer-ci.yml
@@ -18,7 +18,8 @@ jobs:
 
     steps:
       # - run: docker run --init --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=1s --health-timeout=1s --health-retries 180 -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next
-      - run: docker run --init --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=5s --health-timeout=5s --health-retries 60 -d -p 3000:3000 --expose 9229 -p 9229:9229 -v "$(pwd):/home/project:cached" theiaide/theia:next --inspect=0.0.0.0:9229
+      # - run: docker run --init --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=5s --health-timeout=5s --health-retries 60 -d -p 3000:3000 --expose 9229 -p 9229:9229 -v "$(pwd):/home/project:cached" theiaide/theia:next --inspect=0.0.0.0:9229
+      - run: docker run --init -d -p 3000:3000 --expose 9229 -p 9229:9229 -v "$(pwd):/home/project:cached" theiaide/theia:next --inspect=0.0.0.0:9229
 
       - uses: actions/checkout@v2
 
@@ -27,15 +28,26 @@ jobs:
       - name: Create test data file
         run: cp resources/testProfileData.example.ts resources/testProfileData.ts
 
+      - run: docker ps -a
+
       - run: yarn build
 
       - run: yarn lint
 
-      # - name: sleep
-      #   run: sleep 300
+      - name: sleep
+        run: sleep 30
 
+      - run: docker ps -a
+      - run: curl --fail http://localhost:3000
+
+      - name: sleep
+        run: sleep 30
+
+      - run: curl --fail http://localhost:3000
       # - name: Verify Theia
       #   run: firefox --screenshot screenshots/firefox-test.jpg http://localhost:3000/
+
+      - run: docker ps -a
 
       # - name: Upload screenshot
       #   uses: actions/upload-artifact@v1
